version: 1
labels:

- label: "scope: addon"
  files: 
    - addons/**

- label: "scope: core"
  files: 
    - background/**
    - content-scripts/**

- label: "scope: l10n"
  files: 
    - _locales/**
    - addons-l10n/**

- label: "scope: webpages"
  files: 
    - popups/**
    - webpages/**

- label: "scope: meta"
  files: 
    - ".github/**"
    - "!.github/workflows/*"
    - "*"
    - "!*/**"

- label: "scope: ci"
  files: 
    - .github/workflows/*